### PR TITLE
Add the stellar mass - stellar age plot to the pipeline

### PR DESCRIPTION
**Pull request by MatthieuSchaller**
Implements #15. 

Note that the units associated to the ages by VR are odd. They seem to be somehow read in as 9 * 10^9 yrs or something like that. I used the registration.py script to clean up and associated the correct units.

### CODE REVIEW

**Comment by JBorrow** [comment]
This doesn't seem to be the right way to solve this problem at all to me. It seems that the units in the VR file are incorrect.

The reason they are what they are is because they are in code time units, derived from velocity and length.

**Comment by MatthieuSchaller** [comment]
Agreed. They are somehow computed as years but given the wrong units.

**Comment by JBorrow** [comment]
Ok; I am not happy merging this as it creates inconsistencies with the internal unit system. We should remedy this within velociraptor itself.

**Comment by MatthieuSchaller** [comment]
Ok. Let's keep this out for now then and I'll open an issue on the VR side.

BTW, the results are terrible...
stellar_mass_stellar_ages_30

**Comment by JBorrow** [comment]
Lol how is this consistent with zero of the galaxies being quenched

**Pull request closed without merging**
