### PR TITLE
Additional parameter for webpage

### PR DESCRIPTION
**Pull request by sylviaploeckinger**
Added some more parameters to the webpage for COLIBRE, shouldn't break anything for XL.

### CODE REVIEW

**Comment by JBorrow** [comment]
Are you happy for me to edit this or would you prefer things to respond to?

**Comment by sylviaploeckinger** [comment]
Sure, feel free to edit! I put tons of try: except: statements there, especially for the AGN, because not all parameters are always present (sometimes depending on branch, some of them are optional).

**Comment by JBorrow** [comment]
I've made some minor formatting changes, can you check that you're happy with them?

**Comment by sylviaploeckinger** [comment]
Looks good! Thanks!

**Pull request merged**
