### PR TITLE
Add links to return to the top of the page

### PR DESCRIPTION
**Pull request by MatthieuSchaller**
Nothing else to add :)

Implements #9.

### CODE REVIEW

**Comment by JBorrow** [comment]
What is `font size=+2` there for? Happy to add a style called `totop` or something to the CSS.

**Comment by MatthieuSchaller** [comment]
Do we have a CSS? 

The change in font size is me making the section "titles"  larger since they are demoted from `<h1/>`.

**Comment by JBorrow** [comment]
The css is inlined at the top of the page.

How about under each header we have:

```
<a href="#">Back To Top</a>
```

As just a basic line underneath each header? So:

```
<h1>Title Name</h1>
<a href="#">Back To Top</a>
<div class="plots">
...
```

**Comment by MatthieuSchaller** [comment]
That's also fine by me. I was trying to not have additional lines but if you are happy with them, then let's do that.

**Comment by MatthieuSchaller** [comment]
Done.

**Pull request merged**
